### PR TITLE
updated doc/Makefile.am to remove dependencies on achbench.html and o…

### PR DESCRIPTION
**Pull request by varunagrawal**
…ther man2html files

### CODE REVIEW

**Comment by varunagrawal** [comment]
The build is still failing though due to some issues in ach_klinux.c in the 'chan-lock' function:

    DKMS make.log for ach-klinux-2.0.0 for kernel 3.19.0-28-generic (x86_64)
    Tue Sep 15 03:27:49 UTC 2015
    make[4]: Entering directory `/usr/src/linux-headers-3.19.0-28-generic'
    LD      /var/lib/dkms/ach-klinux/2.0.0/build/built-in.o
    CC [M]  /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.o
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c: In function ‘chan_lock’:
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:125:2: error: too many arguments to function ‘rt_mutex_lock_interruptible’
    int i = rt_mutex_lock_interruptible(&chan->shm->sync.mutex, 0);
    ^
    In file included from /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:55:0:
    include/linux/rtmutex.h:93:12: note: declared here
    extern int rt_mutex_lock_interruptible(struct rt_mutex *lock);
                ^
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c: In function ‘ach_ch_close’:
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:490:2: error: too many arguments to function ‘rt_mutex_lock_interruptible’
    if (rt_mutex_lock_interruptible(&ctrl_data.lock, 1)) {
    ^
    In file included from /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:55:0:
    include/linux/rtmutex.h:93:12: note: declared here
    extern int rt_mutex_lock_interruptible(struct rt_mutex *lock);
                ^
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c: In function ‘ach_ch_open’:
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:511:2: error: too many arguments to function ‘rt_mutex_lock_interruptible’
    if (rt_mutex_lock_interruptible(&ctrl_data.lock, 1)) {
    ^
    In file included from /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:55:0:
    include/linux/rtmutex.h:93:12: note: declared here
    extern int rt_mutex_lock_interruptible(struct rt_mutex *lock);
                ^
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c: In function ‘ach_ch_ioctl’:
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:584:4: error: too many arguments to function ‘rt_mutex_lock_interruptible’
        if (rt_mutex_lock_interruptible(&ch_file->shm->sync.mutex, 0)) {
        ^
    In file included from /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:55:0:
    include/linux/rtmutex.h:93:12: note: declared here
    extern int rt_mutex_lock_interruptible(struct rt_mutex *lock);
                ^
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c: In function ‘ach_ctrl_ioctl’:
    /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:910:2: error: too many arguments to function ‘rt_mutex_lock_interruptible’
    if (rt_mutex_lock_interruptible(&ctrl_data.lock, 1)) {
    ^
    
    In file included from /var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.c:55:0:
    include/linux/rtmutex.h:93:12: note: declared here
    extern int rt_mutex_lock_interruptible(struct rt_mutex *lock);
                ^
    make[5]: *** [/var/lib/dkms/ach-klinux/2.0.0/build/ach_klinux.o] Error 1
    make[4]: *** [_module_/var/lib/dkms/ach-klinux/2.0.0/build] Error 2
    make[4]: Leaving directory `/usr/src/linux-headers-3.19.0-28-generic'

Any ideas what I should do to make this work?

**Comment by ndantam** [comment]
Please check if the kernel module changes in ach branch linux-3.18.16-rt compile against your kernel.  Unfortunately, the Linux kernel API changes frequently, so it may be necessary to track multiple API versions.  Perhaps this deserves a mention in the README and/or manual.

Unconditionally disabling man page generation is not a maintainable option because the documentation does sometimes need to be built.  What is the specific error you are still seeing regarding manpage generation?  Did the previous commit and/or `configure --disable-documentation` not resolve your issue?

**Comment by ndantam** [comment]
94022f78fab4ee697ae349ed4d54fe254baed9f2

I missed the HTML manpage in the earlier commit.  Now fixed.

**Comment by varunagrawal** [comment]
Nope, even in the linux-3.18.16-rt branch the build is failing with the following error:

    Making install in src/klinux/dkms-post
    make[2]: Entering directory `/home/varun/golems/ach/src/klinux/dkms-post'
    make[3]: Entering directory `/home/varun/golems/ach/src/klinux/dkms-post'
    make[3]: Nothing to be done for `install-exec-am'.
    if test -n "`dkms status ach-klinux/2.0.0`"; then \
                    dkms remove ach-klinux/2.0.0 --all; \
            fi
    /bin/bash: dkms: command not found
    dkms add /usr/local/src/ach-klinux-2.0.0
    /bin/bash: dkms: command not found
    make[3]: *** [install-data-local] Error 127
    make[3]: Leaving directory `/home/varun/golems/ach/src/klinux/dkms-post'
    make[2]: *** [install-am] Error 2
    make[2]: Leaving directory `/home/varun/golems/ach/src/klinux/dkms-post'
    make[1]: *** [install-recursive] Error 1
    make[1]: Leaving directory `/home/varun/golems/ach'
    make: *** [install] Error 2

**Comment by varunagrawal** [comment]
I tried configuring the build with 
     ./configure  --enable-dkms=yes --enable-dkms-build=yes

**Comment by ndantam** [comment]
Looks like you need to install dkms.

-ntd

**Comment by ndantam** [comment]
Closing with 94022f7

**Pull request closed without merging**
